apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: Application
metadata:
  name: base-chat-document-assistant
  namespace: arcadia
spec:
  displayName: "AI文档对话助手"
  description: "最简单的AI文档对话助手"
  prologue: "Hello, I am a document assistant 🤖"
  nodes:
    - name: Input
      displayName: "用户输入"
      description: "用户输入节点，必须"
      ref:
        kind: Input
        name: Input
      nextNodeName: ["prompt-node"]
    - name: prompt-node
      displayName: "prompt"
      description: "设定prompt，template中可以使用{{xx}}来替换变量"
      ref:
        apiGroup: prompt.arcadia.kubeagi.k8s.com.cn
        kind: Prompt
        name: base-chat-document-assistant
      nextNodeName: ["chain-node"]
    - name: documentloader-node
      displayName: "documentloader"
      description: "设定prompt，template中可以使用{{xx}}来替换变量"
      ref:
        apiGroup: arcadia.kubeagi.k8s.com.cn
        kind: DocumentLoader
        name: base-chat-document-assistant
      nextNodeName: ["chain-node"]
    - name: llm-node
      displayName: "大模型服务"
      description: "设定大模型的访问信息"
      ref:
        apiGroup: arcadia.kubeagi.k8s.com.cn
        kind: LLM
        name: app-shared-llm-service
      nextNodeName: ["chain-node"]
    - name: chain-node
      displayName: "llm chain"
      description: "chain是langchain的核心概念，llmChain用于连接prompt和llm"
      ref:
        apiGroup: chain.arcadia.kubeagi.k8s.com.cn
        kind: LLMChain
        name: base-chat-document-assistant
      nextNodeName: ["Output"]
    - name: Output
      displayName: "最终输出"
      description: "最终输出节点，必须"
      ref:
        kind: Output
        name: Output
---
apiVersion: prompt.arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: Prompt
metadata:
  name: base-chat-document-assistant
  namespace: arcadia
  annotations:
    arcadia.kubeagi.k8s.com.cn/input-rules: '[{"kind":"Input","length":1}]'
    arcadia.kubeagi.k8s.com.cn/output-rules: '[{"length":1}]'
spec:
  displayName: "设定AI文档助手的prompt"
  description: "设定AI文档助手的prompt"
  userMessage: |
    Help me 
    '{{.question}}'
---
apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: DocumentLoader
metadata:
  name: base-chat-document-assistant
  namespace: arcadia
spec:
  displayName: "llm chain"
  description: "llm chain"
  chunkSize: 500
  chunkOverlap: 100
---
apiVersion: chain.arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: LLMChain
metadata:
  name: base-chat-document-assistant
  namespace: arcadia
  annotations:
    arcadia.kubeagi.k8s.com.cn/input-rules: '[{"kind":"LLM","group":"arcadia.kubeagi.k8s.com.cn","length":1},{"kind":"prompt","group":"prompt.arcadia.kubeagi.k8s.com.cn","length":1}]'
    arcadia.kubeagi.k8s.com.cn/output-rules: '[{"kind":"Output","length":1}]'
spec:
  displayName: "llm chain"
  description: "llm chain"
  memory:
    conversionWindowSize: 2
  model: glm-4
