name: Build KubeAGI Data Processing images

on:
  pull_request:
    branches: [main]
    paths:
      - 'pypi/data-processing'
  workflow_dispatch:

jobs:
  test_image_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          config-inline: |
            [worker.oci]
              max-parallelism = 1
      - name: Build Data Procesing image
        uses: docker/build-push-action@v5
        with:
          context: ./pypi/data-processing
          file: ./pypi/data-processing/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
